services:
  app:
    build:
      context: .
      target: frankenphp_prod
    env_file: [".env.local"]
    environment:
      DATABASE_URL: "postgresql://app:app@database:5432/app?serverVersion=15&charset=utf8"
    ports:
      - { target: 80, published: 80, protocol: tcp }
      - { target: 443, published: 443, protocol: tcp }
      - { target: 443, published: 443, protocol: udp }
    depends_on: [database]
    restart: unless-stopped
  app_queue:
    build:
      context: .
      target: frankenphp_prod
    env_file: [".env.local"]
    environment:
      DATABASE_URL: "postgresql://app:app@database:5432/app?serverVersion=15&charset=utf8"
    command: ["bin/console", "messenger:consume", "async", "-v"]
    depends_on: [database]
    restart: unless-stopped
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
    ports: [5432:5432]
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    restart: unless-stopped

volumes:
  database_data:
