version: "3"

tasks:
  fmt:
    desc: Format everything
    deps: [fmt:php, fmt:caddy, fmt:other]
  fmt:php:
    desc: Format php files
    sources:
      - "**/*.php"
    cmds:
      - docker compose exec app vendor/bin/php-cs-fixer fix
  fmt:caddy:
    desc: Format the Caddyfile
    sources:
      - "docker/caddy/Caddyfile"
    cmds:
      - docker compose run --rm app frankenphp fmt --overwrite /etc/caddy/Caddyfile
  fmt:other:
    desc: Format other files
    sources:
      - "**/*.yaml"
      - "./assets/**/*.js"
      - "*.js"
      - "./assets/**/*.css"
    cmds:
      - npx prettier -w .

  lint:
    desc: Lint everything
    deps: [lint:php, lint:symfony, lint:twig, lint:lang]
  lint:php:
    desc: Lint php files
    sources:
      - "**/*.php"
      - "phpstan.dist.neon"
    cmds:
      - vendor/bin/phpstan --memory-limit=-1 analyze
  lint:symfony:
    desc: Lint symfony configuration
    sources:
      - "config/**/*.yaml"
    cmds:
      - bin/console lint:container
      - bin/console lint:yaml config
  lint:twig:
    desc: Lint twig files
    sources:
      - "templates/**/*.twig"
    cmds:
      - bin/console lint:twig templates
  lint:lang:
    desc: Lint spelling
    sources:
      - "**/*.php"
      - "**/*.yaml"
      - "**/*.twig"
    cmds:
      - typos
