version: "3"

tasks:
  run:
    internal: true
    cmds:
      - silent: true
        cmd: |
          if ! command -v docker &> /dev/null
          then
              {{.CMD}}
          else
              docker compose exec app {{.CMD}}
          fi

  fmt:
    desc: Format everything
    deps: [fmt:php, fmt:caddy, fmt:other]
  fmt:php:
    desc: Format php files
    sources: ["**/*.php"]
    cmds:
      - { task: run, vars: { CMD: "php vendor/bin/php-cs-fixer fix" } }
  fmt:caddy:
    desc: Format the Caddyfile
    sources: ["docker/caddy/Caddyfile"]
    cmds:
      - { task: run, vars: { CMD: "frankenphp fmt --overwrite /etc/caddy/Caddyfile" } }
  fmt:other:
    desc: Format other files
    sources: ["**/*.yaml", "./assets/**/*.js", "*.js", "./assets/**/*.css", "./assets/**/*.json"]
    cmds:
      - npx prettier -w .

  lint:
    desc: Lint everything
    deps: [lint:composer, lint:php, lint:symfony, lint:doctrine, lint:twig, lint:lang]
  lint:composer:
    desc: Lint composer files
    sources: ["composer.json", "composer.lock"]
    cmds:
      - { task: run, vars: { CMD: "composer validate" } }
  lint:php:
    desc: Lint php files
    sources: ["**/*.php", "phpstan.dist.neon"]
    cmds:
      - { task: run, vars: { CMD: "php vendor/bin/phpstan --memory-limit=-1 analyze" } }
  lint:symfony:
    desc: Lint symfony configuration
    sources: ["config/**/*.yaml"]
    cmds:
      - { task: run, vars: { CMD: "bin/console lint:container" } }
      - { task: run, vars: { CMD: "bin/console lint:yaml config" } }
  lint:doctrine:
    desc: Lint doctrine mapping
    sources: ["src/Entity/**/*.php", "migrations/**/*.php"]
    cmds:
      - { task: run, vars: { CMD: "bin/console doctrine:migrations:migrate --no-interaction" } }
      - { task: run, vars: { CMD: "bin/console doctrine:schema:validate" } }
  lint:twig:
    desc: Lint twig files
    sources: ["templates/**/*.twig"]
    cmds:
      - { task: run, vars: { CMD: "bin/console lint:twig templates" } }
  lint:lang:
    desc: Lint spelling
    sources: ["**/*.php", "**/*.yaml", "**/*.twig", "_typos.toml"]
    cmds:
      - typos
