version: "3"

tasks:
  fmt:php:
    desc: Format php files
    sources:
      - "**/*.php"
    cmds:
      - vendor/bin/php-cs-fixer fix
  fmt:caddy:
    desc: Format the Caddyfile
    sources:
      - "docker/caddy/Caddyfile"
    cmds:
      - docker compose run --rm web caddy fmt --overwrite /etc/caddy/Caddyfile
  fmt:other:
    desc: Format other files
    sources:
      - "**/*.yaml"
    cmds:
      - npx prettier -w .
